### ISSUE TITLE
dcn compile errors

### ISSUE THREAD

**Issue by TensorTom** [open-mmlab/mmsr#84] opened 2020-05-28 00:02 UTC
Trying to compile dcn with `python setup.py develop` produces:

```
src/deform_conv_cuda.cpp: In function ‘void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
src/deform_conv_cuda.cpp:65:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK(weight.ndimension() == 4,
   ^~~~~~~~
src/deform_conv_cuda.cpp:65:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK(weight.ndimension() == 4,
   ^~~~~~~~
   DCHECK
src/deform_conv_cuda.cpp: In function ‘int deform_conv_forward_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
src/deform_conv_cuda.cpp:192:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
   ^~~~~~~~
src/deform_conv_cuda.cpp:192:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
   ^~~~~~~~
   DCHECK
src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_input_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
src/deform_conv_cuda.cpp:298:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
   ^~~~~~~~
src/deform_conv_cuda.cpp:298:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
   ^~~~~~~~
   DCHECK
src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_parameters_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, float, int)’:
src/deform_conv_cuda.cpp:413:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
   ^~~~~~~~
src/deform_conv_cuda.cpp:413:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
   ^~~~~~~~
   DCHECK
src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
src/deform_conv_cuda.cpp:493:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
   ^~~~~~~~
src/deform_conv_cuda.cpp:493:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
   ^~~~~~~~
   DCHECK
src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
src/deform_conv_cuda.cpp:574:3: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
   ^~~~~~~~
src/deform_conv_cuda.cpp:574:3: note: suggested alternative: ‘DCHECK’
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
   ^~~~~~~~
   DCHECK
error: command 'gcc' failed with exit status 1
```

**Comment by ryul99** [comment] 2020-06-01 07:52
If you are using pytorch 1.5, I think this solution can solve your problem
https://github.com/xinntao/EDVR/issues/146#issue-615087838

**Comment by dmmartindale** [comment] 2020-06-16 19:43
Yes, the problem is that mmsr has not been updated to support pytorch 1.5, which is what you get if you install pytorch via anaconda now.

There have been several reports of the same problem with the same source files in the mmdetection project; see issue #2513 in that project.  This was fixed by releasing version 2.0 of mmdetection; see issue #2618 and 2619.  If you look at the revision history of the files deform_conv_cuda.cpp and deform_conv_cuda_kernel.cu in the master branch of mmdetection, you can see what was changed in version 2.0.

You cannot simply copy the two source files from mmdetection source tree into mmsr's source directory; there are a few differences between the files.  Instead, you can either do a pair-wise compare of the two files and copy across only the relevant changes, or just hand-edit the source files within mmsr's source directory.  The changes needed are:

In deform_conv_cuda.cpp, change all occurrences of AT_CHECK to TORCH_CHECK.

In deform_conv_cuda_kernel.cu, find all of the occurrences of
    data_col.data
    data_im.data
    data_mask.data
    data_offset.data
    grad_im.data
    grad_offset.data
    grad_mask.data
and add the string "_ptr" to each.  I.e. data_col.data becomes data_col.data_ptr.

In addition, there appears to be one bug in the second file that has been corrected in mmdetection.  In line 821 of the source, an argument list includes "pad_h, pad_h" where mmdetection's version of the code passes "pad_h, pad_w".  I changed this to agree with mmdetection.

With these changes, the dcn compile succeeds.  (Ubuntu 18.04.4 LTS, GCC 7.5.0, Anaconda with Python 3.7.6, CUDA 10.1, Pytorch 1.5.

**Comment by davdmc** [comment] 2020-06-26 13:20
It seems to compile for me. I hope they add this fix soon!

**Comment by xinntao** [comment] 2020-07-08 13:36
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
This feature will be updated in MMEditing.

**Closed by xinntao** 2020-07-08 13:36 UTC
